export const IMG = {
  hero1: "/portfolio/hero-veil-kiss.jpg",
  hero2: "/portfolio/hero-garden-processional.jpg",
  hero3: "/portfolio/hero-champagne-tower.jpg",
  about1: "/portfolio/about-window-portrait.jpg",
  about2: "/portfolio/about-flatlay-table.jpg",
  gal1: "/portfolio/gallery-bride-garden.jpg",
  gal2: "/portfolio/gallery-venue-lawn.jpg",
  gal3: "/portfolio/gallery-fruit-florals.jpg",
  gal4: "/portfolio/gallery-couple-buffet.jpg",
  gal5: "/portfolio/gallery-bridal-portrait.jpg",
  gal6: "/portfolio/gallery-signage-detail.jpg",
  gal7: "/portfolio/gallery-wedding-party.jpg",
  gal8: "/portfolio/gallery-cake-florals.jpg",
  svc1: "/portfolio/service-styled-chandelier.jpg",
  svc2: "/portfolio/service-wedding-portrait.jpg",
  svc3: "/portfolio/service-editorial-table.jpg",
  svc4: "/portfolio/service-creative-direction.jpg",
  cta: "/portfolio/cta-reception-room.jpg",
} as const;
